### PR TITLE
Feature ignore glob

### PR DESCRIPTION
**Pull request by kbl**
New feature - supporting ignore globs mentioned in issue #8.

### CODE REVIEW

**Comment by copiousfreetime** [comment]
I believe some of my recent comments no longer make this pull request cleanly apply. I was working on Issue #16 and found a few more bugs that I had introduce. 

@TwP you want to merge this after @kbl does a rebase?

**Comment by TwP** [comment]
It has been a while, but did you already implement this feature Jeremy with your refactorings?

**Comment by copiousfreetime** [comment]
No, I didn't implement ignore.

**Comment by kbl** [comment]
Should I rebase this code?

**Comment by copiousfreetime** [comment]
yes, I would say do a rebase.

**Comment by copiousfreetime** [comment]
Actually, It will probably be easier to just pull out the ignore globs functionality and skip all the test rearrangement

**Comment by copiousfreetime** [comment]
Closing this pull request as it is stale. A new pull requests for this feature should be submitted that is rebased against master.

**Pull request closed without merging**
