### PR TITLE
Coolio

### PR DESCRIPTION
**Pull request by namelessjon**
I've modified DirectoryWatcher to use the new Coolio gem instead of Rev.  It's more or less a find and replace patch, but I also added an alias so that `:scanner => :rev` will continue to work.  I've only tested it on 1.9.2, because that's all I have to hand.

### CODE REVIEW

**Comment by TwP** [comment]
Thanks for tackling this. Does it make more sense to keep a rev scanner around and have a completely separate cool.io scanner for the sake of backwards compatibility? That is my only thought on this one.

**Comment by namelessjon** [comment]
Perhaps that might be better, yes.  If I get time later today, I'll update the pull request.

I have no data on rev vs coolio usage, and how much people have upgraded, so I suppose it makes sense to support both

**Comment by namelessjon** [comment]
There, updated my branch to add an independent Coolio scanner, instead of replacing the old Rev scanner.

**Comment by namelessjon** [comment]
Just following up on this pull request:  Are there any problems with it?

**Comment by TwP** [comment]
No problems ... just have not taken the time to look at the changes yet. Life and the day job have been very full leaving little time for open source side projects.

**Pull request merged**
